!do ->
  # run on debounced scroll event and once on load
  # debounced scroll event

  _scroll = (a, b) ->
    window.addEventListener('scroll', ->
      clearTimeout b
      b = setTimeout(a, 200)
      return
    )
    a

  # main function wrapper

  lazyestload = ->
    # all the images with class lazyestload
    images = document.querySelectorAll('img.lazyestload')
    i = images.length
    # loop de loop
    while i--
      wH = window.innerHeight
      boundingRect = images[i].getBoundingClientRect()
      offset = 100
      yPositionTop = boundingRect.top - wH
      yPositionBottom = boundingRect.bottom
      # if the top of the image is within 100px from the bottom of the viewport
      # and if the bottom of the image is within 100px from the top of the viewport
      # basically if the image is in the viewport, with a bit of buffer
      if yPositionTop <= offset and yPositionBottom >= -offset
        # replace the src with the data-src
        if images[i].getAttribute('data-src')
          images[i].src = images[i].getAttribute('data-src')
        # replace the srcset with the data-srcset
        if images[i].getAttribute('data-srcset')
          images[i].srcset = images[i].getAttribute('data-srcset')
        # replace the source srcset's with the data-srcset's
        if images[i].parentElement.tagName == 'PICTURE'
          sources = images[i].parentElement.querySelectorAll('source')
          j = sources.length
          while j--
            sources[j].srcset = sources[j].getAttribute('data-srcset')
        # wait until the new image is loaded
        images[i].addEventListener 'load', ->
          @classList.remove 'lazyestload'
          return
    return

  _scroll(->
    lazyestload()
    return
  )()
  return

# ---
# generated by js2coffee 2.2.0
